### ISSUE TITLE
Missing spatialite module on MacOS

### ISSUE THREAD

**Issue by edigonzales** [opengisch/QgisModelBaker#275]
Creating a GeoPackage does not work on MacOS. Does not find spatialite module:

```
Traceback (most recent call last):
  File "/Users/stefan/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/QgisModelBaker/gui/generate_project.py", line 257, in accepted
    configuration.inheritance, configuration.dbschema)
  File "/Users/stefan/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/QgisModelBaker/libqgsprojectgen/generator/generator.py", line 46, in __init__
    self._db_connector = gpkg_connector.GPKGConnector(uri, None)
  File "/Users/stefan/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/QgisModelBaker/libqgsprojectgen/dbconnector/gpkg_connector.py", line 33, in __init__
    self.conn = qgis.utils.spatialite_connect(uri)
  File "/Applications/QGIS3.4.3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 615, in spatialite_connect
    raise RuntimeError("Cannot find any suitable spatialite module")
RuntimeError: Cannot find any suitable spatialite module
```

Python version: 3.7.1 (default, Nov 28 2018, 11:51:47) [Clang 10.0.0 (clang-1000.11.45.5)] 
QGIS version: 3.4.3-Madeira Madeira, 2f64a3c4e7

**Comment by m-kuhn** [comment]
Looks more like a QGIS upstream issue.
Can you take the computer to our next meeting?

**Comment by romefi** [comment]
Closing for lack of feedback. Please re-open if it's still an issue.
