### ISSUE TITLE
Python Authentication Fails (psycopg2)

### ISSUE THREAD

**Issue by zigertiger** [opengisch/QgisModelBaker#362]
We work with QGIS 3.4 LTR and we utilise KERBEROS authentication systemwide. 

When trying to generate a QGIS project from an existing PostGIS schema, an Python error is thrown immediately. The error is thrown whether a passwort ist submitted or not (system password is used).

`Ein Fehler trat bei der Ausführung von Python-Code auf: 

psycopg2.ProgrammingError: column full_name.owner does not exist LINE 27:                                        ON full_name.owner='...                                                     ^ 
Traceback (most recent call last):
  File "C:/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\gui\generate_project.py", line 263, in accepted
    available_layers = generator.layers()
  File "C:/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\libqgsprojectgen\generator\generator.py", line 100, in layers
    fields_info = self.get_fields_info(record['tablename'])
  File "C:/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\libqgsprojectgen\generator\generator.py", line 268, in get_fields_info
    return self._db_connector.get_fields_info(table_name)
  File "C:/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\libqgsprojectgen\dbconnector\pg_connector.py", line 303, in get_fields_info
    full_name_join=full_name_join))
  File "C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\psycopg2\extras.py", line 144, in execute
    return super(DictCursor, self).execute(query, vars)
psycopg2.ProgrammingError: column full_name.owner does not exist
LINE 27:                                         ON full_name.owner='...
                                                    ^

Python-Version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS-Version: 3.4.13-Madeira Madeira, 64ad560274 `

So, we cannot work with the ModelBaker at the moment...

**Comment by zigertiger** [comment]
Yes, we tried the plugin version 5.0.2

**Comment by m-kuhn** [comment]
This looks like a conflict of ili2db versions used for creating the database and generating the project. But 5.0.2 should handle this gracefully with ili2db3 and ili2db4 created databases, so there is an issue.

How was the database created?

**Comment by zigertiger** [comment]
ili2pg 4.x

**Comment by m-kuhn** [comment]
> ili2pg 4.x

Can you be slightly more verbose :)

**Comment by zigertiger** [comment]
Manually. I use ili2pg from the command line. Normally, the Model Baker is (shall be) "only" used to create a QGIS Project from an existing schema, or, to import/export Data.

**Comment by zigertiger** [comment]
At the moment, we are working with ili2pg 4.3.1. But of course, not all the schemas are created with exactly the same program version.

I normally apply the following command options:

`
ili2pg.jar --schemaimport --createTidCol --coalesceCatalogueRef --createEnumTabs --createNumChecks --coalesceMultiSurface --coalesceMultiLine --coalesceMultiPoint --coalesceArray --beautifyEnumDispName --createUnique --createGeomIdx --createFk --createFkIdx --createMetaInfo --createBasketCol --smart1Inheritance --defaultSrsCode 2056 --setupPgExt --disableValidation --dbhost #SERVER# --dbusr #USER# --dbpwd '#PWD#' --dbdatabase #DB#--dbschema ch_ausnahmetransportrouten --models ExceptionalLoadsRoute_LV95_V1
`

**Comment by zigertiger** [comment]
As I mentioned beforehand, our computer infrastructure handles authentication with KERBEROS and AcitveDirectory.
So, we do not need to submit a user name or a password when we connect to PostGIS from QGIS e.g. We have another issue with the ModelBaker and ili2pg since the JDBC authentication does not work with our KERBEROS environment as a whole. Our developers are on track to fix that issue.
But the mentioned psycopg2-error seems to have a different source.

I just wanted to make clear that we cannot work with the ModelBaker at all at the moment, but we think that this error does not have the same origin as the KERBEROS-JDBC-ili2pg error...

**Comment by m-kuhn** [comment]
Thank you for the information. This is certainly a ili2db version issue (i.e. the error comes from the database, authentication is already successful and a connection established at this point)

@signedav , can you have a look at this?

**Comment by m-kuhn** [comment]
Can you try to install https://github.com/opengisch/QgisModelBaker/releases/download/5.0.0-beta1/QgisModelBaker.5.0.0-beta1.zip (manually)?

**Comment by zigertiger** [comment]
Trying to manually install 5.0.0-beta1 throws an error:

`
Konnte Erweiterung 'QgisModelBaker' nicht laden aufgrund eines Fehlers beim Aufruf der classFactory() Methode 

ModuleNotFoundError: No module named 'packaging' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\__init__.py", line 23, in classFactory
    from .qgismodelbaker import QgisModelBakerPlugin
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 685, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\qgismodelbaker.py", line 24, in 
    from QgisModelBaker.gui.generate_project import GenerateProjectDialog
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 685, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\gui\generate_project.py", line 27, in 
    from QgisModelBaker.gui.options import OptionsDialog, CompletionLineEdit
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 685, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\gui\options.py", line 23, in 
    from QgisModelBaker.libqgsprojectgen.db_factory.db_simple_factory import DbSimpleFactory
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 685, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\libqgsprojectgen\db_factory\db_simple_factory.py", line 19, in 
    from .db_factory import DbFactory
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 685, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\libqgsprojectgen\db_factory\db_factory.py", line 21, in 
    from QgisModelBaker.libili2db.ili2dbconfig import Ili2DbCommandConfiguration
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 685, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\libili2db\ili2dbconfig.py", line 21, in 
    from QgisModelBaker.libili2db.ili2dbutils import get_all_modeldir_in_path
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 685, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\libili2db\ili2dbutils.py", line 28, in 
    from packaging import version
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 685, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'packaging'


Python-Version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS-Version: 3.4.13-Madeira Madeira, 64ad560274 
`

**Comment by m-kuhn** [comment]
Is it possible to stick to ili2db3 for database creation for the moment?

**Comment by zigertiger** [comment]
Unfortunately not, since we accomplished a significant effort to migrate all schemas from ili2pg3 to ili2pg4...

**Comment by zigertiger** [comment]
...but the problem has prevailed since quite a period --- first, we thought that it has to do with our KERBEROS environment. We just realised that it has another cause.

That means we do need a solution as soon as possible, BUT! we are not facing an all new, absoulte show stopper here...

**Comment by m-kuhn** [comment]
Can you try version [QgisModelBaker-5.0.0-beta2.zip](https://github.com/opengisch/QgisModelBaker/files/4044834/QgisModelBaker-5.0.0-beta2.zip)

**Comment by zigertiger** [comment]
Now, this seems to work! I could achieve a successful QGIS project generation from an existing PG schema by bypassing the passwort (using KERBEROS).
![pg2qgs](https://user-images.githubusercontent.com/25387992/72144795-68d4a280-3399-11ea-94ce-a8225a95c2cf.PNG)

We stick with the known ili2pg-JDBC-authentication problem. But this is an issue for our developers...
Thanks!

**Comment by m-kuhn** [comment]
Thank you,
let's close this issue in this case
