### ISSUE TITLE
ModuleNotFoundError when installing Model Baker 5.0.2

### ISSUE THREAD

**Issue by pramisters** [opengisch/QgisModelBaker#366]
```
Couldn't load plugin 'QgisModelBaker' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'pyodbc' 
Traceback (most recent call last):
  File "C:/Programme/OSGeo4W64/apps/qgis-rel-dev/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/KANU/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\__init__.py", line 23, in classFactory
    from .qgismodelbaker import QgisModelBakerPlugin
  File "C:/Programme/OSGeo4W64/apps/qgis-rel-dev/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/KANU/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\qgismodelbaker.py", line 24, in 
    from QgisModelBaker.gui.generate_project import GenerateProjectDialog
  File "C:/Programme/OSGeo4W64/apps/qgis-rel-dev/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/KANU/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\gui\generate_project.py", line 27, in 
    from QgisModelBaker.gui.options import OptionsDialog, CompletionLineEdit
  File "C:/Programme/OSGeo4W64/apps/qgis-rel-dev/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/KANU/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\gui\options.py", line 23, in 
    from QgisModelBaker.libqgsprojectgen.db_factory.db_simple_factory import DbSimpleFactory
  File "C:/Programme/OSGeo4W64/apps/qgis-rel-dev/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/KANU/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\libqgsprojectgen\db_factory\db_simple_factory.py", line 22, in 
    from .mssql_factory import MssqlFactory
  File "C:/Programme/OSGeo4W64/apps/qgis-rel-dev/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/KANU/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\libqgsprojectgen\db_factory\mssql_factory.py", line 20, in 
    from ..dbconnector.mssql_connector import MssqlConnector
  File "C:/Programme/OSGeo4W64/apps/qgis-rel-dev/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/KANU/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\libqgsprojectgen\dbconnector\mssql_connector.py", line 21, in 
    import pyodbc
  File "C:/Programme/OSGeo4W64/apps/qgis-rel-dev/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'pyodbc'


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.10.2-A Coruña A Coruña, d4cd3cfe5a 
```
Both Windows  10 and Windows 7 !

**Comment by m-kuhn** [comment]
Thank you for the feedback, @pramisters 
I had the same last week on Fedora.

@gacarrillor what do you think, we should probably disable MSSQL support if pyodbc is missing (and show that in the about page with installation instructions).

**Comment by m-kuhn** [comment]
@pramisters just to be sure: installed via osgeo4w or standalone installer?

**Comment by pramisters** [comment]
Both osgeo4w.

But I just tried a standalone version (3.4.2), too.
--> No error here !

**Comment by pramisters** [comment]
Found and installed pyodbc (3.0.7-1) via osgeo4w.
Still the same problem.

**Comment by gacarrillor** [comment]
> @gacarrillor what do you think, we should probably disable MSSQL support if pyodbc is missing (and show that in the about page with installation instructions).

Sounds like the way to go. I'll let @yesidpol know about it. I think this is something we can work on after PR #324 is merged. In the meantime, we could:

 + Add a try/except block to this import: https://github.com/opengisch/QgisModelBaker/blob/master/QgisModelBaker/libqgsprojectgen/db_factory/db_simple_factory.py#L22

 + Remove `DbIliMode.mssql` from https://github.com/opengisch/QgisModelBaker/blob/master/QgisModelBaker/libqgsprojectgen/db_factory/db_simple_factory.py#L30

What do you think, @m-kuhn?

**Comment by m-kuhn** [comment]
Yes, this sounds good.

It would be good to already do this in parallel since it affects the latest (ili2db3 based) release.

**Comment by m-kuhn** [comment]
Yes, this sounds very good! Thanks.
