### ISSUE TITLE
XTF Export: GSS Authentication Error

### ISSUE THREAD

**Issue by zigertiger** [opengisch/QgisModelBaker#435]
We work with KERBEROS to handle user authentication in general.

When trying to exort INTERLIS transfer data from an existing PostGIS-schema to an XTF file, a GSS Authentication error is thrown:

```
C:/Program Files/Java/jre1.8.0_261/bin/javaw.exe -jar C:\Users\peter.staub\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\QgisModelBaker\libili2db\bin\ili2pg-4.4.3\ili2pg-4.4.3.jar --dbhost srv-gis-01.glnet.ch --dbusr peter.staub --dbdatabase glarus --dbschema gl_waldbestaende --export --models GL_Waldbestaende_V1 C:/Users/peter.staub/Desktop/test.xtf
Info: dburl <jdbc:postgresql://srv-gis-01.glnet.ch/glarus>
Info: dbusr <peter.staub>
Okt 02, 2020 1:38:29 PM org.postgresql.Driver connect
SCHWERWIEGEND: Connection error: 
org.postgresql.util.PSQLException: GSS Authentication failed
	at org.postgresql.gss.MakeGSS.authenticate(MakeGSS.java:66)
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:594)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:222)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:194)
	at org.postgresql.Driver.makeConnection(Driver.java:450)
	at org.postgresql.Driver.connect(Driver.java:252)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at ch.ehi.ili2db.base.AbstractJdbcMapping.connect(AbstractJdbcMapping.java:31)
	at ch.ehi.ili2db.base.Ili2db.connect(Ili2db.java:1804)
	at ch.ehi.ili2db.base.Ili2db.readSettingsFromDb(Ili2db.java:189)
	at ch.ehi.ili2db.AbstractMain.domain(AbstractMain.java:553)
	at ch.ehi.ili2pg.PgMain.main(PgMain.java:70)
Caused by: javax.security.auth.login.LoginException: Für pgjdbc sind keine LoginModules konfiguriert
	at javax.security.auth.login.LoginContext.init(Unknown Source)
	at javax.security.auth.login.LoginContext.<init>(Unknown Source)
	at org.postgresql.gss.MakeGSS.authenticate(MakeGSS.java:56)
	... 13 more

GSS Authentication failed
  Für pgjdbc sind keine LoginModules konfiguriert
Info: ili2pg-4.4.3-658b7daf37ba45ed2330ca3e3a3c3d59c96e91fa
Info: ili2c-5.1.0-20200501
Info: iox-ili-1.21.0-731076775d8b9bd0599802cf5a0324bc3a1c21d8
Info: java.version 1.8.0_261
Info: user.name <peter.staub>
Info: maxMemory 1820672 KB
Info: currentTime 2020-10-02 13:38:29
Info: dbschema <gl_waldbestaende>
Info: dburl <jdbc:postgresql://srv-gis-01.glnet.ch/glarus>
Info: dbusr <peter.staub>
Okt 02, 2020 1:38:29 PM org.postgresql.Driver connect
SCHWERWIEGEND: Connection error: 
org.postgresql.util.PSQLException: GSS Authentication failed
	at org.postgresql.gss.MakeGSS.authenticate(MakeGSS.java:66)
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:594)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:222)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:194)
	at org.postgresql.Driver.makeConnection(Driver.java:450)
	at org.postgresql.Driver.connect(Driver.java:252)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at ch.ehi.ili2db.base.AbstractJdbcMapping.connect(AbstractJdbcMapping.java:31)
	at ch.ehi.ili2db.base.Ili2db.connect(Ili2db.java:1804)
	at ch.ehi.ili2db.base.Ili2db.runExport(Ili2db.java:1546)
	at ch.ehi.ili2db.base.Ili2db.run(Ili2db.java:225)
	at ch.ehi.ili2db.AbstractMain.domain(AbstractMain.java:555)
	at ch.ehi.ili2pg.PgMain.main(PgMain.java:70)
Caused by: javax.security.auth.login.LoginException: Für pgjdbc sind keine LoginModules konfiguriert
	at javax.security.auth.login.LoginContext.init(Unknown Source)
	at javax.security.auth.login.LoginContext.<init>(Unknown Source)
	at org.postgresql.gss.MakeGSS.authenticate(MakeGSS.java:56)
	... 14 more

java.lang.NullPointerException
Finished (1)
```

We are not quite shure whether this seems to be an issue of the plugin or rather a misconfiguration of our it environment. We would be very grateful if you could take a quick look and clarify the situation...

thx and sorry for the helplessness, Peter

**Comment by m-kuhn** [comment]
Hi Peter,

Is this specific to export or also for import / creating schema?

The best guess is a [missing jaas config file](https://www.postgresql.org/message-id/CALBNtw7dxJscEtnDAkxfQ6YKBQZmoW6FEQifUPSYwaD5t24TeQ%40mail.gmail.com) which would be environment related.

**Comment by zigertiger** [comment]
Export only...
Config/import work just fine...

**Comment by m-kuhn** [comment]
Now that is truly surprising.
What happens if you launch the same commands from the command line?

**Comment by zigertiger** [comment]
OK, dumb me.
My fault: GSS authentication error occurs when I attempt to
- configure a new schema
- import transfer data
- export transfer data 
via Model Baker.

The Model Baker works quite OK upon an already existing schema. 

I guess that's an issue for our IT...
