### ISSUE TITLE
Installation of Version 6.3.2 not quite fine

### ISSUE THREAD

**Issue by zigertiger** [opengisch/QgisModelBaker#454]
Currently, I'm working with QGIS LTR 3.10.9 and QGIS Model Baker 6.2.0.

Upon installation of version 6.3.2, a python error was thrown, but nevertheless, version 6.3.2 was actually installed. But it doesn't work, so I had to downgrade to version 6.2.0 again.

Installation error:

```
Konnte Erweiterung 'QgisModelBaker' nicht laden aufgrund eines Fehlers beim Aufruf der classFactory() Methode 

ModuleNotFoundError: No module named 'packaging' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/peter.staub/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\__init__.py", line 23, in classFactory
    from .qgismodelbaker import QgisModelBakerPlugin
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/peter.staub/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\qgismodelbaker.py", line 26, in 
    from QgisModelBaker.gui.generate_project import GenerateProjectDialog
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/peter.staub/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\gui\generate_project.py", line 27, in 
    from QgisModelBaker.gui.options import OptionsDialog, CompletionLineEdit
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/peter.staub/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\gui\options.py", line 23, in 
    from QgisModelBaker.libqgsprojectgen.db_factory.db_simple_factory import DbSimpleFactory
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/peter.staub/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\libqgsprojectgen\db_factory\db_simple_factory.py", line 19, in 
    from .db_factory import DbFactory
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/peter.staub/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\libqgsprojectgen\db_factory\db_factory.py", line 21, in 
    from QgisModelBaker.libili2db.ili2dbconfig import Ili2DbCommandConfiguration
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/peter.staub/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\libili2db\ili2dbconfig.py", line 21, in 
    from QgisModelBaker.libili2db.ili2dbutils import get_all_modeldir_in_path
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/peter.staub/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\libili2db\ili2dbutils.py", line 33, in 
    from packaging import version
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'packaging'
```

**Comment by m-kuhn** [comment]
Thanks for reporting

**Comment by gacarrillor** [comment]
Just to let you know that this is still occurring in v6.3.2, installed via QGIS plugin repo.
The GitHub release is fine: https://github.com/opengisch/QgisModelBaker/releases/download/v6.3.2/QgisModelBaker.v6.3.2.zip,
but the Zip file in the QGIS plugin repo is not.

**Comment by signedav** [comment]
Thanks a lot @gacarrillor There has been obviously a problem in the upload with the same tag. I'll have a look today.
