### ISSUE TITLE
invalid dsn: invalid connection option "authcfg" 

### ISSUE THREAD

**Issue by romefi** [opengisch/QgisModelBaker#472]
I'm trying to generate a project with the auth-configuration:

![image](https://user-images.githubusercontent.com/26796989/107615277-250f3500-6c4c-11eb-9d00-923fef86a750.png)

This configuration works fine when PostGIS-Layers are added over Datenquellverwaltung. In Model Baker I recieve this error:

```
Ein Fehler trat bei der Ausführung von Python-Code auf: 

psycopg2.ProgrammingError: invalid dsn: invalid connection option "authcfg" 
Traceback (most recent call last):
  File "C:/Users/rfill/AppData/Roaming/QGIS/QGIS3\profiles\Standard/python/plugins\QgisModelBaker\gui\generate_project.py", line 225, in accepted
    configuration = self.updated_configuration()
  File "C:/Users/rfill/AppData/Roaming/QGIS/QGIS3\profiles\Standard/python/plugins\QgisModelBaker\gui\generate_project.py", line 473, in updated_configuration
    configuration.db_ili_version = self.db_ili_version(configuration)
  File "C:/Users/rfill/AppData/Roaming/QGIS/QGIS3\profiles\Standard/python/plugins\QgisModelBaker\gui\generate_project.py", line 445, in db_ili_version
    db_connector = db_factory.get_db_connector(uri_string, schema)
  File "C:/Users/rfill/AppData/Roaming/QGIS/QGIS3\profiles\Standard/python/plugins\QgisModelBaker\libqgsprojectgen\db_factory\pg_factory.py", line 32, in get_db_connector
    return PGConnector(uri, schema)
  File "C:/Users/rfill/AppData/Roaming/QGIS/QGIS3\profiles\Standard/python/plugins\QgisModelBaker\libqgsprojectgen\dbconnector\pg_connector.py", line 37, in __init__
    self.conn = psycopg2.connect(uri)
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\psycopg2\__init__.py", line 125, in connect
    dsn = _ext.make_dsn(dsn, **kwargs)
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\psycopg2\extensions.py", line 152, in make_dsn
    parse_dsn(dsn)
psycopg2.ProgrammingError: invalid dsn: invalid connection option "authcfg"



Python-Version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS-Version: 3.16.1-Hannover Hannover, b381a90dca 

Python-Pfad:
C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python
C:/Users/rfill/AppData/Roaming/QGIS/QGIS3\profiles\Standard/python
C:/Users/rfill/AppData/Roaming/QGIS/QGIS3\profiles\Standard/python/plugins
C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS3~1.16\apps\Python37
C:\PROGRA~1\QGIS3~1.16\apps\Python37\Scripts
C:\Program Files\QGIS 3.16\bin\python37.zip
C:\PROGRA~1\QGIS3~1.16\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib
C:\Program Files\QGIS 3.16\bin
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\Pythonwin
C:/Users/rfill/AppData/Roaming/QGIS/QGIS3\profiles\Standard/python
```

Any idea what causes the problem?

**Comment by signedav** [comment]
Hi @romefi 
Is this still the case when you test? and did that work once?

**Comment by signedav** [comment]
It's because you cannot use the authentification config without using the super user password / username. There won't be an error anymore, but a warning log with #541
