### ISSUE TITLE
Problems when dropping XTF Files

### ISSUE THREAD

**Issue by signedav** [opengisch/QgisModelBaker#546]
Dropping an XTF from outside to QGIS leads to this issue.
(If not handled over Model Baker).

```
2021-09-29T16:30:40     WARNING    Traceback (most recent call last):
              File "/home/dave/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QgisModelBaker/gui/panel/dataset_selector.py", line 147, in set_current_layer
              db_factory.get_db_connector(
              File "/home/dave/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QgisModelBaker/libqgsprojectgen/db_factory/gpkg_factory.py", line 31, in get_db_connector
              return GPKGConnector(uri, None)
              File "/home/dave/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QgisModelBaker/libqgsprojectgen/dbconnector/gpkg_connector.py", line 52, in __init__
              self._bMetadataTable = self._metadata_exists()
              File "/home/dave/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QgisModelBaker/libqgsprojectgen/dbconnector/gpkg_connector.py", line 77, in _metadata_exists
              cursor.execute(
             sqlite3.DatabaseError: file is not a database

```

**Comment by signedav** [comment]
Apparently an XTF is handled as QGR Source in QGIS, what leads to this error since we check if it's a valid source (like PG, MSSQL or OGR), but this is not.
