### ISSUE TITLE
unable to install from qgis plugin manager

### ISSUE THREAD

**Issue by bwakkie** [opengisch/QgisModelBaker#626]
Couldn't load plugin 'QgisModelBaker' due to an error when calling its initGui() method 

TypeError: setMaximumHeight(self, int): argument 1 has unexpected type 'float' 
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/qgis/utils.py", line 448, in startPlugin
    plugins[packageName].initGui()
  File "/home/sliss/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QgisModelBaker/qgismodelbaker.py", line 245, in initGui
    self.init_validate_dock()
  File "/home/sliss/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QgisModelBaker/qgismodelbaker.py", line 441, in init_validate_dock
    self.__validate_dock = ValidateDock(self.ili2db_configuration, self.iface)
  File "/home/sliss/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QgisModelBaker/gui/validate.py", line 253, in __init__
    self.filter_data_panel.setMaximumHeight(self.height() / 4)
TypeError: setMaximumHeight(self, int): argument 1 has unexpected type 'float'

Python version: 3.10.1 (main, Dec 18 2021, 23:53:45) [GCC 11.1.0] 
QGIS version: 3.22.2-Białowieża Białowieża, exported 

Python Path:
/usr/share/qgis/python
/home/sliss/.local/share/QGIS/QGIS3/profiles/default/python
/home/sliss/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python310.zip
/usr/lib/python3.10
/usr/lib/python3.10/lib-dynload
/usr/lib/python3.10/site-packages
/home/sliss/.local/share/QGIS/QGIS3/profiles/default/python
/home/sliss/.local/share/QGIS/QGIS3/profiles/default/python/plugins/HCMGIS/forms
/home/sliss/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgisgbifapi/vendor
/home/sliss/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgisgbifapi/vendor
/home/sliss/.local/share/QGIS/QGIS3/profiles/default/python/plugins/postgisQueryBuilder
/home/sliss/.local/share/QGIS/QGIS3/profiles/default/python/plugins/postgisQueryBuilder/extlibs

**Comment by signedav** [comment]
Thanks. I will have a look.
