### ISSUE TITLE
sqlite3.OperationalError: near "-": syntax error when enabling QGIS Model Baker

### ISSUE THREAD

**Issue by mrtwister3142** [opengisch/QgisModelBaker#639]
With QGIS Model Baker Version 7.0.3 and QGIS 3.22.3-1 I get at startup oder when manually enabling QGIS Model Baker:
```
An error has occurred while executing Python code: 

sqlite3.OperationalError: near "-": syntax error 
Traceback (most recent call last):
  File "C:\Users/Mv/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\gui\validate.py", line 362, in _visibility_changed
    self.set_current_layer(self.iface.activeLayer())
  File "C:\Users/Mv/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\gui\validate.py", line 347, in set_current_layer
    self._refresh_schemadata_models()
  File "C:\Users/Mv/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\gui\validate.py", line 365, in _refresh_schemadata_models
    db_connector = db_utils.get_db_connector(self.current_configuration)
  File "C:\Users/Mv/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\utils\db_utils.py", line 116, in get_db_connector
    return db_factory.get_db_connector(uri_string, schema)
  File "C:\Users/Mv/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\libqgsprojectgen\db_factory\gpkg_factory.py", line 31, in get_db_connector
    return GPKGConnector(uri, None)
  File "C:\Users/Mv/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\libqgsprojectgen\dbconnector\gpkg_connector.py", line 53, in __init__
    self._tables_info = self._get_tables_info()
  File "C:\Users/Mv/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\libqgsprojectgen\dbconnector\gpkg_connector.py", line 197, in _get_tables_info
    cursor.execute(
sqlite3.OperationalError: near "-": syntax error


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.22.3-Białowieża Białowieża, 1628765ec7 

Python Path:
C:/OSGeo4W/apps/qgis/./python
C:/Users/Mv/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Mv/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGeo4W/apps/qgis/./python/plugins
C:\OSGeo4W\bin\python39.zip
C:\OSGeo4W\apps\Python39\DLLs
C:\OSGeo4W\apps\Python39\lib
C:\OSGeo4W\bin
C:\Users\Mv\AppData\Roaming\Python\Python39\site-packages
C:\OSGeo4W\apps\Python39
C:\OSGeo4W\apps\Python39\lib\site-packages
C:\OSGeo4W\apps\Python39\lib\site-packages\GDAL-3.4.1-py3.9-win-amd64.egg
C:\OSGeo4W\apps\Python39\lib\site-packages\win32
C:\OSGeo4W\apps\Python39\lib\site-packages\win32\lib
C:\OSGeo4W\apps\Python39\lib\site-packages\Pythonwin
C:/Users/Mv/AppData/Roaming/QGIS/QGIS3\profiles\default/python
```
I have no issues with QGIS 3.16.16-1 and Model Baker 7.0.3.

**Comment by signedav** [comment]
What is your active layer when this happens?

**Comment by mrtwister3142** [comment]
a GPKG-layer

**Comment by signedav** [comment]
what's the name of the table in the gpkg?

**Comment by mrtwister3142** [comment]
it happens with differen tables, e.g. "Baggersondierungen" or "Kugelfang_Mittelpunkte"

**Comment by signedav** [comment]
Some queries are not that rocket proof. We need to consider this to solve such problems https://github.com/opengisch/QgisModelBaker/issues/604

**Comment by signedav** [comment]
Hm... still those tables should not make problems :thinking:

**Comment by signedav** [comment]
What is again the version of Model Baker and QGIS? I assume you mean Model Baker version 7.0.3 right? 
Then you have the issue on QGIS 3.22 with the same Model Baker like not having the issue on QGIS 3.16?

**Comment by mrtwister3142** [comment]
sorry you are right, Model Baker 7.0.3 with QGIS 3.22.3-1

**Comment by mrtwister3142** [comment]
no issues with QGIS 3.16.16

**Comment by mrtwister3142** [comment]
Just had a similar issue while having a _shapefile_ layer active:

```
2022-02-18T15:27:51     WARNING    Traceback (most recent call last):
              File "C:\Users/Mv/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\gui\validate.py", line 347, in set_current_layer
              self._refresh_schemadata_models()
              File "C:\Users/Mv/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\gui\validate.py", line 365, in _refresh_schemadata_models
              db_connector = db_utils.get_db_connector(self.current_configuration)
              File "C:\Users/Mv/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\utils\db_utils.py", line 116, in get_db_connector
              return db_factory.get_db_connector(uri_string, schema)
              File "C:\Users/Mv/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\libqgsprojectgen\db_factory\gpkg_factory.py", line 31, in get_db_connector
              return GPKGConnector(uri, None)
              File "C:\Users/Mv/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\libqgsprojectgen\dbconnector\gpkg_connector.py", line 52, in __init__
              self._bMetadataTable = self._metadata_exists()
              File "C:\Users/Mv/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\libqgsprojectgen\dbconnector\gpkg_connector.py", line 77, in _metadata_exists
              cursor.execute(
             sqlite3.DatabaseError: file is not a database
```

Happens with with QGIS 3.22.3-1 _and_ QGIS 3.16.16.

**Comment by signedav** [comment]
I just labeled it as bug. If you could attach a demo data it would help to reproduce. Thanks.

**Comment by mrtwister3142** [comment]
Meanwhile I realised that the issues happens with layers using a filter query or joined fields (shapefiles and geopackages). Still looking for demo data (I am not the data owner of the files throwing the error...).

**Comment by mrtwister3142** [comment]
[test.zip](https://github.com/opengisch/QgisModelBaker/files/8416192/test.zip)
Please try the attached demo data. With this I get:
```
2022-04-05T10:11:43     WARNING    Traceback (most recent call last):
              File "C:\Users/_/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\gui\validate.py", line 347, in set_current_layer
              self._refresh_schemadata_models()
              File "C:\Users/_/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\gui\validate.py", line 365, in _refresh_schemadata_models
              db_connector = db_utils.get_db_connector(self.current_configuration)
              File "C:\Users/_/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\utils\db_utils.py", line 116, in get_db_connector
              return db_factory.get_db_connector(uri_string, schema)
              File "C:\Users/_/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\libqgsprojectgen\db_factory\gpkg_factory.py", line 31, in get_db_connector
              return GPKGConnector(uri, None)
              File "C:\Users/_/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\libqgsprojectgen\dbconnector\gpkg_connector.py", line 52, in __init__
              self._bMetadataTable = self._metadata_exists()
              File "C:\Users/_/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\libqgsprojectgen\dbconnector\gpkg_connector.py", line 77, in _metadata_exists
              cursor.execute(
             sqlite3.DatabaseError: file is not a database
```

**Comment by mrtwister3142** [comment]
Exactly the same issue is reoccurring with QGIS 3.28 and QgisModelBaker 7.2.6 when clicking on a gpkg layer.

> With QGIS Model Baker Version 7.0.3 and QGIS 3.22.3-1 I get at startup oder when manually enabling QGIS Model Baker:
> 
> ```
> An error has occurred while executing Python code: 
> 
> sqlite3.OperationalError: near "-": syntax error 
> Traceback (most recent call last):
>   File "C:\Users/Mv/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\gui\validate.py", line 362, in _visibility_changed
>     self.set_current_layer(self.iface.activeLayer())
>   File "C:\Users/Mv/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\gui\validate.py", line 347, in set_current_layer
>     self._refresh_schemadata_models()
>   File "C:\Users/Mv/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\gui\validate.py", line 365, in _refresh_schemadata_models
>     db_connector = db_utils.get_db_connector(self.current_configuration)
>   File "C:\Users/Mv/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\utils\db_utils.py", line 116, in get_db_connector
>     return db_factory.get_db_connector(uri_string, schema)
>   File "C:\Users/Mv/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\libqgsprojectgen\db_factory\gpkg_factory.py", line 31, in get_db_connector
>     return GPKGConnector(uri, None)
>   File "C:\Users/Mv/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\libqgsprojectgen\dbconnector\gpkg_connector.py", line 53, in __init__
>     self._tables_info = self._get_tables_info()
>   File "C:\Users/Mv/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\libqgsprojectgen\dbconnector\gpkg_connector.py", line 197, in _get_tables_info
>     cursor.execute(
> sqlite3.OperationalError: near "-": syntax error
> [...]

**Comment by signedav** [comment]
Okay. This is with GeoPackage again. I think we fixed the issue with Shapefile. Could you please add a test-project for the issue with GeoPackage. Thanks.
