### ISSUE TITLE
Cannot create project for non superuser user

### ISSUE THREAD

**Issue by signedav** [opengisch/QgisModelBaker#702]
On creating a schema with super user but having the project created for a user without super user rights I receive the error:
```
An error has occurred while executing Python code: 

AssertionError 
Traceback (most recent call last):
  File "/home/cheapdave/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QgisModelBaker/gui/workflow_wizard/project_creation_page.py", line 248, in _create_project
    project.create(None, qgis_project)
  File "/home/cheapdave/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QgisModelBaker/libs/modelbaker/dataobjects/project.py", line 119, in create
    assert rel.isValid()
AssertionError


Python version: 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0] 
QGIS version: 3.24.3-Tisler Tisler, e4feab1714 
```

But this is not the main problem. The problem is that even when the superuser sets AUTORIZATION of the schema on the user, this user cannot perform selects (and with this load the QGIS layers) because it does not has rights on the tables. Here a grant would be needed.

**Comment by signedav** [comment]
@andreasneumann Did you experienced the same? Or do you only use super users in your service files?
