### ISSUE TITLE
UsabILIty Hub Topping Exporter: Opening wizzard fails

### ISSUE THREAD

**Issue by romefi** [opengisch/QgisModelBaker#726]
We get this error when we try to open the UsabILIty Hub Topping Exporter on an existing Model Baker project:

```
2022-09-13T08:31:08     WARNING    Traceback (most recent call last):
              File "C:\Users/macke/AppData/Roaming/QGIS/QGIS3\profiles\Standard_3_22/python/plugins\QgisModelBaker\qgismodelbaker.py", line 353, in show_topping_wizard_dialog
              self.topping_wizard_dlg = ToppingWizardDialog(
              File "C:\Users/macke/AppData/Roaming/QGIS/QGIS3\profiles\Standard_3_22/python/plugins\QgisModelBaker\gui\topping_wizard\topping_wizard.py", line 116, in __init__
              self.topping_wizard = ToppingWizard(self.iface, self.base_config, self)
              File "C:\Users/macke/AppData/Roaming/QGIS/QGIS3\profiles\Standard_3_22/python/plugins\QgisModelBaker\gui\topping_wizard\topping_wizard.py", line 62, in __init__
              self.layers_page = LayersPage(
              File "C:\Users/macke/AppData/Roaming/QGIS/QGIS3\profiles\Standard_3_22/python/plugins\QgisModelBaker\gui\topping_wizard\layers_page.py", line 414, in __init__
              self.layermodel = LayerModel(
              File "C:\Users/macke/AppData/Roaming/QGIS/QGIS3\profiles\Standard_3_22/python/plugins\QgisModelBaker\gui\topping_wizard\layers_page.py", line 110, in __init__
              self.reload()
              File "C:\Users/macke/AppData/Roaming/QGIS/QGIS3\profiles\Standard_3_22/python/plugins\QgisModelBaker\gui\topping_wizard\layers_page.py", line 250, in reload
              self._set_default_values()
              File "C:\Users/macke/AppData/Roaming/QGIS/QGIS3\profiles\Standard_3_22/python/plugins\QgisModelBaker\gui\topping_wizard\layers_page.py", line 309, in _set_default_values
              if self._is_ili_schema(layernode.layer()):
              File "C:\Users/macke/AppData/Roaming/QGIS/QGIS3\profiles\Standard_3_22/python/plugins\QgisModelBaker\gui\topping_wizard\layers_page.py", line 291, in _is_ili_schema
              source_provider = layer.dataProvider()
             AttributeError: 'NoneType' object has no attribute 'dataProvider'
```

**Comment by signedav** [comment]
On every project? To avoid the crash it's an easy fix, but I wonder why specific layers return none...

**Comment by romefi** [comment]
It's only if there are non available layers in the project and you choose "nicht vefügbare Layer behalten".

![image](https://user-images.githubusercontent.com/26796989/190182076-208f143c-1137-447a-a6f8-28ff80e395bd.png)

**Comment by signedav** [comment]
Yes. Makes sense. Will be fixed in the next patch release.
