### ISSUE TITLE
sqlite3.OperationalError:near".":syntax error

### ISSUE THREAD

**Issue by DadoooR3** [opengisch/QgisModelBaker#853]
Hello,
I'm trying to use Model Baker on Opensuse tumbleweed.
The installation seems to have gone very well, I load a geopackage, but it does not go well.
I'm sorry I'm not up to speed on deferring problems.
Thanks for your help.

I get this error message:

sqlite3.OperationalError: near ".": syntax error 
Traceback (most recent call last):
  File "/home/daniel/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QgisModelBaker/gui/workflow_wizard/database_selection_page.py", line 133, in nextId
    return self.workflow_wizard.next_id()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daniel/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QgisModelBaker/gui/workflow_wizard/workflow_wizard.py", line 234, in next_id
    self._update_configurations(self.generate_database_selection_page)
  File "/home/daniel/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QgisModelBaker/gui/workflow_wizard/workflow_wizard.py", line 426, in _update_configurations
    page.update_configuration(self.import_schema_configuration)
  File "/home/daniel/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QgisModelBaker/gui/workflow_wizard/database_selection_page.py", line 109, in update_configuration
    configuration.db_ili_version = db_utils.db_ili_version(configuration)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daniel/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QgisModelBaker/libs/modelbaker/utils/db_utils.py", line 152, in db_ili_version
    db_connector = get_db_connector(configuration)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daniel/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QgisModelBaker/libs/modelbaker/utils/db_utils.py", line 128, in get_db_connector
    return db_factory.get_db_connector(uri_string, schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daniel/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QgisModelBaker/libs/modelbaker/db_factory/gpkg_factory.py", line 29, in get_db_connector
    return GPKGConnector(uri, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daniel/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QgisModelBaker/libs/modelbaker/dbconnector/gpkg_connector.py", line 52, in __init__
    self._tables_info = self._get_tables_info()
                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daniel/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QgisModelBaker/libs/modelbaker/dbconnector/gpkg_connector.py", line 271, in _get_tables_info
    cursor.execute(
sqlite3.OperationalError: near ".": syntax error

Version de Python : 3.11.6 (main, Nov 15 2023, 09:22:27) [GCC] 
Version de QGIS : 3.32.3-Lima Lima, exported 

Chemin Python :
/usr/share/qgis/python
/home/daniel/.local/share/QGIS/QGIS3/profiles/default/python
/home/daniel/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib64/python311.zip
/usr/lib64/python3.11
/usr/lib64/python3.11/lib-dynload
/home/daniel/.local/lib/python3.11/site-packages
/usr/lib64/python3.11/site-packages
/usr/lib64/python3.11/site-packages/PIL
/usr/lib64/python3.11/_import_failed
/usr/lib/python3.11/site-packages
/home/daniel/.local/share/QGIS/QGIS3/profiles/default/python

**Comment by signedav** [comment]
Hard to say. Would be great if you could provide the Geopackage or the Model you use.

**Comment by signedav** [comment]
No problem. Even with broken dataset Model Baker should not error like this. But anyway - come back to it, when you encounter it again or have other questions. I close it for now.
