### ISSUE TITLE
Data validation of baskets with empty t_ili_tid fails

### ISSUE THREAD

**Issue by webrian** [opengisch/QgisModelBaker#957]
* a database schema with three datasets, each of the dataset has one basket
* since the import was done _without_ `--importBid` the t_ili_tid column is empty, see the database table:

![grafik](https://github.com/user-attachments/assets/6fa0a2e1-0093-4151-aefc-f7d27dd1acf1)

* the baskets in the Model Baker Data Validator widget:

![grafik](https://github.com/user-attachments/assets/941a0f88-40cb-4c4b-9cda-c587b0c72dcd)

the basket validation fails with:

```
Traceback (most recent call last):
  File "C:\Users/bjsvwweb/AppData/Roaming/QGIS/QGIS3\profiles\INTEGRATION/python/plugins\QgisModelBaker\gui\validate.py", line 391, in _run
    self._validator_stdout(f"Run: {validator.command(True)}")
  File "C:\Users/bjsvwweb/AppData/Roaming/QGIS/QGIS3\profiles\INTEGRATION/python/plugins\QgisModelBaker\libs\modelbaker\iliwrapper\iliexecutable.py", line 99, in command
    args = self._args(hide_password)
  File "C:\Users/bjsvwweb/AppData/Roaming/QGIS/QGIS3\profiles\INTEGRATION/python/plugins\QgisModelBaker\libs\modelbaker\iliwrapper\ilivalidator.py", line 42, in _args
    args = super()._args(hide_password)
  File "C:\Users/bjsvwweb/AppData/Roaming/QGIS/QGIS3\profiles\INTEGRATION/python/plugins\QgisModelBaker\libs\modelbaker\iliwrapper\iliexecutable.py", line 80, in _args
    return get_ili2db_args(self.configuration, hide_password)
  File "C:\Users/bjsvwweb/AppData/Roaming/QGIS/QGIS3\profiles\INTEGRATION/python/plugins\QgisModelBaker\libs\modelbaker\iliwrapper\ili2dbargs.py", line 40, in get_ili2db_args
    return configuration.to_ili2db_args(db_args)
  File "C:\Users/bjsvwweb/AppData/Roaming/QGIS/QGIS3\profiles\INTEGRATION/python/plugins\QgisModelBaker\libs\modelbaker\iliwrapper\ili2dbconfig.py", line 451, in to_ili2db_args
    self.append_args(args, ["--baskets", ";".join(self.baskets)])
TypeError: sequence item 0: expected str instance, NoneType found
```

* filling an id into the t_ili_id column:

![grafik](https://github.com/user-attachments/assets/75928746-8358-460a-b0f8-c42032be9b8a)

the validation works!
It is the same issue in the export Wizard as well.

**Comment by signedav** [comment]
The bug here is that baskets without t_ili_tid are provided to the selection in the validator...
