### ISSUE TITLE
Java-Error Model Baker 7.10.5 - Error Description

### ISSUE THREAD

**Issue by MlchiR** [opengisch/QgisModelBaker#996]
Following up on the post (https://interlis.discourse.group/t/java-error-mit-model-baker-7-10-5/342) in the Interlis forum, which reported an error occurring during import after the ModelBaker update of 2.12.2024, I'm posting my error messages here. Perhaps this will help you further.
What I did:
Opening ModelBaker and trying to import an ili model from the repository.
I wanted the data to be written into a locally stored GeoPackage file.
After finding the ili from the repository, during the step "Schema Import Sessions" the error occurred.
I got the following messages additionally to similar messages that were shown in the post in the Interlis discourse group.

--------------------------

2024-12-03T09:49:32     WARNING    There was an error connecting to the database. Check connection parameters. Error details: connection to server at "localhost" (::1), port 5432 failed: Connection refused (0x0000274D/10061)
              Is the server running on that host and accepting TCP/IP connections?
             connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused (0x0000274D/10061)
              Is the server running on that host and accepting TCP/IP connections?
             
2024-12-03T09:49:32     WARNING    There was an error connecting to the database. Check connection parameters. Error details: connection to server at "localhost" (::1), port 5432 failed: Connection refused (0x0000274D/10061)
              Is the server running on that host and accepting TCP/IP connections?
             connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused (0x0000274D/10061)
              Is the server running on that host and accepting TCP/IP connections?
             
2024-12-03T09:49:32     WARNING    There was an error connecting to the database. Check connection parameters. Error details: connection to server at "localhost" (::1), port 5432 failed: Connection refused (0x0000274D/10061)
              Is the server running on that host and accepting TCP/IP connections?
             connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused (0x0000274D/10061)
              Is the server running on that host and accepting TCP/IP connections?
             
2024-12-03T09:50:00     WARNING    There was an error connecting to the database. Check connection parameters. Error details: connection to server at "localhost" (::1), port 5432 failed: Connection refused (0x0000274D/10061)
              Is the server running on that host and accepting TCP/IP connections?
             connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused (0x0000274D/10061)
              Is the server running on that host and accepting TCP/IP connections?
             
2024-12-03T09:50:21     WARNING    There was an error connecting to the database. Check connection parameters. Error details: [Errno 2] No such file or directory: 'C:/Users/michaela.ramsauer/MRa/MRa/AR_Windpotenzial_V1.gpkg'
2024-12-03T09:50:21     WARNING    There was an error connecting to the database. Check connection parameters. Error details: [Errno 2] No such file or directory: 'C:/Users/michaela.ramsauer/MRa/MRa/AR_Windpotenzial_V1.gpkg'
2024-12-03T09:50:21     WARNING    There was an error connecting to the database. Check connection parameters. Error details: [Errno 2] No such file or directory: 'C:/Users/michaela.ramsauer/MRa/MRa/AR_Windpotenzial_V1.gpkg'
2024-12-03T09:50:21     WARNING    There was an error connecting to the database. Check connection parameters. Error details: [Errno 2] No such file or directory: 'C:/Users/michaela.ramsauer/MRa/MRa/AR_Windpotenzial_V1.gpkg'
2024-12-03T09:50:21     WARNING    There was an error connecting to the database. Check connection parameters. Error details: [Errno 2] No such file or directory: 'C:/Users/michaela.ramsauer/MRa/MRa/AR_Windpotenzial_V1.gpkg'

.......................................

Python-Message:

2024-12-03T09:50:25     WARNING    Traceback (most recent call last):
              File "C:\Users/michaela.ramsauer/AppData/Roaming/QGIS/QGIS3\profiles\RaM/python/plugins\QgisModelBaker\gui\workflow_wizard\workflow_wizard.py", line 436, in id_changed
              self.import_schema_execution_page.setup_sessions(
              File "C:\Users/michaela.ramsauer/AppData/Roaming/QGIS/QGIS3\profiles\RaM/python/plugins\QgisModelBaker\gui\workflow_wizard\execution_page.py", line 121, in setup_sessions
              session = SessionPanel(
              File "C:\Users/michaela.ramsauer/AppData/Roaming/QGIS/QGIS3\profiles\RaM/python/plugins\QgisModelBaker\gui\panel\session_panel.py", line 125, in __init__
              self.tr(
             KeyError: 'Modelle'
             
----------------------------------

Here the softwareinformations to qgis:

QGIS-Version
3.34.5-Prizren
QGIS-Codeversion
4b308492
Qt-Version
5.15.3
Python-Version
3.9.18
GDAL-Version
3.8.4
PROJ-Version
9.3.1
EPSG-Registraturdatenbankversion
v10.098 (2023-11-24)
GEOS-Version
3.12.1-CAPI-1.18.1
SQLite-Version
3.41.1
PDAL-Version
2.6.0
PostgreSQL-Client-Version
16.2
SpatiaLite-Version
5.1.0
QWT-Version
6.1.6
QScintilla2-Version
2.13.4
BS-Version
Windows 10 Version 2009

Aktive Python-Erweiterungen
latlontools
3.7.2
linking_relation_editor
v1.4.0
QgisModelBaker
v7.10.5
quick_map_services
0.19.36
swiss_locator
3.0.1
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99

.................................................................
I was wondering if this only occurs when one tries to write into a gpkg?
I would be glad for a quick solution to this issue.
Thank you
Michi

**Comment by signedav** [comment]
Thanks. I can reproduce it and will publish a fix asap.
